name: Run UI Test
run-name: Run UI Test

# 觸發此 action 的時機
on:
  push:
    branches: '*' # 只要有任何一個 commit 被 push，就會觸發此 action
  pull_request:
    branches: '*'
  # schedule:
  #   - cron: "55 16 * * *"
  workflow_dispatch:  # 可以手動執行此 action

# 預先定義此 action 要幹嘛
jobs:
  Run_Twitch_UI_Test:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 讓 actions 有寫入權限
    steps:
      - name: Checkout
        uses: actions/checkout@v3   #actions/checkout@v3 代表 checkout Action 的 主要版本 v3
        with:
          persist-credentials: false  # 停用內建的 GITHUB_TOKEN
      - name: Setup Python
        uses: actions/setup-python@v4.5.0  #v4（2023年發布）：支援 cache、更好的 Python 安裝流程
        with:
          python-version: "3.12"
      - name: Show workspace path
        run: echo "Workspace is at $GITHUB_WORKSPACE"
      - name: Install Python Dependency
        run: pip3 install -r requirements.txt
      - name: Export Path
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: Check if ChromeDriver exists
        id: check_chromedriver
        run: |
          if command -v chromedriver &> /dev/null
          then
            echo "ChromeDriver exists"
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "ChromeDriver not found"
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Install ChromeDriver if not found
        if: env.exists == 'false'
        run: |
          sudo apt update
          sudo apt install -y chromium-chromedriver

      - name: Verify ChromeDriver installation
        run: |
          chromedriver --version
      - name: Run Twitch_Proj/Testcases/test_twitch.py
        run: |
          python3 --version
          pytest --tb=short --html=Twitch_Proj/report.html --self-contained-html Twitch_Proj/Testcases/test_twitch.py || exit 1
          echo "================="
      - name: Commit Data Back To GitHub Repo  # 將測試結果回傳到Github
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
        run: |
          ls -al Twitch_Proj
          echo "================="
          git status
          git config --global user.name "github-actions[bot]" #設定 Git 使用者名稱 為 "github-actions[bot]"（這是 GitHub Actions 的官方機器人帳號）。
          git config --global user.email "github-actions[bot]@users.noreply.github.com" #一個匿名 GitHub Email，避免洩露個人資訊。
          git add .
          git commit -m "daily report and log ,Automated commit from GitHub Actions"  || exit 0 # 防止沒有變更時出錯
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git


